### ISSUE TITLE
bug: Ctrl+R can crash node

### ISSUE THREAD

**Issue by nick1udwig** [uqbar-dao/nectar#524] opened 2024-09-04 14:24 UTC
**Describe the bug**

> in terminal, ctrl + R, then starting to type "state" crashes the node 

https://discord.com/channels/1186394868336038080/1186421052071477428/1280830761670410270

**Expected behavior**
Never crash

**Notes**
Tentatively assigned @dr-frmr ; feel free to offload to me or @bitful-pannul if desired

**Comment by dr-frmr** [comment] 2024-09-04 18:26
FWIW this must be caused by some historical command, because doing this on a fresh node does not crash and I can't repro on a well-used node. I suspect this is directly connected to the crash from special character entry. I know the solution, it's just tedious.. I'll do it soon

**Comment by dr-frmr** [comment] 2024-09-11 21:14
Addressed in #528

**Closed as completed by dr-frmr** 2024-09-11 21:14 UTC
Labels: bug
